#服务端配置
server:
#访问端口
  port: 8080
#访问路径
  context-path: /weyland
#自定义配置项(对应BasicController中的name和securityCode)
name: David
securityCode: 73694-B
record: "record is :  name: ${name}  securityCode: ${securityCode}"
visitor:
  name: my name is David
  securityCode: securityCode 73694-B