#服务端配置
server:
#访问端口
  port: 8081
#访问路径
  context-path: /weyland
#自定义配置项(对应BasicController中的name和securityCode)
name: Walter
securityCode: 31564-F
record: "record is :  name: ${name}  securityCode: ${securityCode}"
visitor:
  name: my name is Walter
  securityCode: securityCode 31564-F